CREATE TABLE submissions (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	type VARCHAR(32) NOT NULL,
	temp VARCHAR(40) NOT NULL,
	name VARCHAR(32) NOT NULL,
	author VARCHAR(32) NOT NULL,
	file VARCHAR(128) NOT NULL,
	description VARCHAR(256),
	version VARCHAR(32),
	categories VARCHAR(256),
	icon VARCHAR(128),
	screenshots VARCHAR(1024),
	tid VARCHAR(4),
	email VARCHAR(128)
);
